// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    BlogCreate: typeof import('./src/views/BlogCreate.vue')['default']
    BlogEditor: typeof import('./src/components/BlogEditor.vue')['default']
    BlogItem: typeof import('./src/components/BlogItem.vue')['default']
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    BlogListWithAsyncLoading: typeof import('./src/components/BlogListWithAsyncLoading.vue')['default']
    BlogMenu: typeof import('./src/components/BlogMenu.vue')['default']
    BlogPagination: typeof import('./src/components/BlogPagination.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCol: typeof import('tdesign-vue-next')['Col']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TRow: typeof import('tdesign-vue-next')['Row']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}

export {}
